languageCode = "en-US"
DefaultContentLanguage = "en"
title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"


[params]
  editURL = "https://github.com/matcornic/hugo-learn-doc/edit/master/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  ordersectionsby = "weight" # ordersectionsby = "title"
  showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
